### ISSUE TITLE
L'ordre d'exécution de certains tests n'est pas garanti

### ISSUE THREAD

**Issue by Dagothig** [IFT2245/TP2-SampleTests#2]
J'omets les `sleep 100` et `exit` parce qu'ils n'ont pas d'impact sur l'ordre d'exécution.

### samples_two
```
1. ls,echo&10,10&2&1&1&20
2. sleep 2 && r2(ls) &
3. whereis printsenpremier && sleep 5 &
4. sleep 2 && whereis printsen2e
```
Comme `ls` est une ressource à part, `2.` n'est pas bloqué par la ressource prise par `3.`. `4.` a seulement besoin d'une seule ressource filesystem alors il n'est pas bloqué non plus.
Comme `2.` et `4.` s'exécutent sur des threads différents (le temps entre `pthread_create` et le début du thread peut varier) et que `sleep` ne garanti pas le temps d'attente (c'est un "au moins"), alors l'ordre entre `r2(ls)` et `whereis printsen2e` n'est pas garanti.

### samples_three
```
1. sleep,echo&30,10&2&1&1&2
2. sleep 2 && r2(cettecommandenexistepas) &
3. imprimeenpremier && sleep 5 &
4. sleep 2 && imprimeendeuxieme
```
Comme un appel de commande invalide est "faux", le `sleep` de `3.` n'est jamais exécuté et la ressource est libérée immédiatement. Alors `2.` n'a pas a attendre la fin de `3.` pour exécuter le `rN`.
Comme `2.` et `4.` s'exécutent sur des threads différents (le temps entre `pthread_create` et le début du thread peut varier) et que `sleep` ne garanti pas le temps d'attente (c'est un "au moins"), alors l'ordre entre `r2(...)` et `imprimeendeuxieme` n'est pas garanti.

### samples_four
```
1. blocker,echo&2,20&2&1&1&20
2. blocker || echo oh_no_il_ma_depassee &
3. r2(blocker) || echo muahahha_je_passe_avant_toi && sleep 5 &
```
Pour des raisons similaires, il y a une condition de course sur le premier `blocker` qui exécute. La ligne qui passe le `blocker` en premier s'exécute toujours au complet avant l'autre (à cause du cap de ressources), mais si c'est `2.` ou `3.` n'est pas garanti.

### samples_five
```
1. blocker,echo&2,20&2&1&1&20
2. blocker || echo je_passe_quand_meme_avant_dawg &
3. r2(blocker) || f1(blocker) && echo muahahha_je_passe_avant_toi && echo surprised_pikachu.jpg && sleep 5 &
```
Il y a une condition de course entre si c'est `2.` ou `3.` qui commence en premier. Si c'est `2.` alors la ligne s'exécute au complet (faute de ressources `blocker`) avant que `3.` puisse commencer. Si c'est `3.` alors une fois que un des `blocker` est relâché alors `2.` peut tout de suite commencer, et l'ordre des `echo` est entièrement non-déterministe.

**Comment by Velythyl** [comment]
Pour samples_2: c'est voulu. C'est pour montrer le constraste avec samples_one.

3: bien vu, j'ai eu de la malchance que mon implémentation fasse fonctionne le tout pareil. J'ai changé le && pour ||

Pour le 4 et 5: je vais retirer ces tests et les retravailler. Le but était surtout de montrer que le bloquage pouvait arriver avec des commandes invalides

**Comment by SamuelYvon** [comment]
@Dagothig 

Avant de fermer le PR, je suis curieux, avais-tu les mêmes résultats (sans tenir compte de l'ordre)? Est-ce que l'ordre était différent?

Pour les `sleep 2` de
```
2. sleep 2 && r2(ls) &
3. whereis printsenpremier && sleep 5 &
4. sleep 2 && whereis printsen2e
```

**Comment by Dagothig** [comment]
En général mon exécution donne le même ordre, mais en lisant le test il me semblait qu'il y avait la même implication que sur les autres... J'ai un changement d'ordre entre le `r2(ls)` et le `whereis printsen2e` peut-être une fois sur 30-40. Sur un `bash` avec un script adapté je ne suis pas sur que j'ai réussi à reproduire un changement d'ordre sur le test 2. Pour le tp c'est finicky de garantir l'ordre vu que c'est très dépendant du temps d'exécution de chaque bout alors j'ai finis par give up et mon script de test utilise un fichier "expect" en plus d'un fichier de test qui peut s'attendre à voir des outputs concurrents...

**Comment by SamuelYvon** [comment]
> peut-être une fois sur 30-40

Intéressant; malheuresement (pour nous) c'est pas acceptable pour corriger. Par contre, le PR de Charlie ajoute une commande qui permet de faire de la synchronisation alors on devrait être correct. 

Merci du bug, je vais merge le PR
